// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSu4HIdVRLldJ1UnBvN8UAia-QSwhaX7A',
    appId: '1:189901509537:web:ac8912b8190dfe32a071e0',
    messagingSenderId: '189901509537',
    projectId: 'expensesxd-manager',
    authDomain: 'expensesxd-manager.firebaseapp.com',
    storageBucket: 'expensesxd-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVQU3LkFNqEi7toP6FL9sXUUHd3pYikU',
    appId: '1:189901509537:android:ba459682c174abb0a071e0',
    messagingSenderId: '189901509537',
    projectId: 'expensesxd-manager',
    storageBucket: 'expensesxd-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfhVdH9bRAju6CCtIFjO3AY5MEXHgd1ag',
    appId: '1:189901509537:ios:e27e50160d79a47fa071e0',
    messagingSenderId: '189901509537',
    projectId: 'expensesxd-manager',
    storageBucket: 'expensesxd-manager.appspot.com',
    iosClientId: '189901509537-nv9qo23ibrm822ld1i52a9m7k7s14pka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myexpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfhVdH9bRAju6CCtIFjO3AY5MEXHgd1ag',
    appId: '1:189901509537:ios:e27e50160d79a47fa071e0',
    messagingSenderId: '189901509537',
    projectId: 'expensesxd-manager',
    storageBucket: 'expensesxd-manager.appspot.com',
    iosClientId: '189901509537-nv9qo23ibrm822ld1i52a9m7k7s14pka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myexpenses',
  );
}
